# Generated by Django 3.0.7 on 2022-06-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image_profil',
            field=models.ImageField(blank=True, upload_to='photos/client'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image_profil',
            field=models.ImageField(blank=True, upload_to='photos/fournisseur'),
        ),
    ]
