# Generated by Django 4.0.5 on 2022-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_add_stock_product_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
