# Generated by Django 4.0.5 on 2022-07-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_stock_final_product_stock_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
