# Generated by Django 4.0.5 on 2022-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
