# Generated by Django 4.0.5 on 2022-07-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
