# Generated by Django 4.0.6 on 2022-07-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_add_stock_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
