# Generated by Django 4.0.5 on 2022-06-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
