# Generated by Django 4.0.6 on 2022-07-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
